/**
 * Utility to interact with MSG91 API for OTP sending and verification.
 * Supports a mock mode for local testing if API credentials are not set.
 */

const getCredentials = () => {
    const authKey = process.env.MSG91_AUTH_KEY;
    const templateId = process.env.MSG91_TEMPLATE_ID;

    const isMock = !authKey || !templateId || 
                   authKey.startsWith('placeholder') || 
                   templateId.startsWith('placeholder');

    return { authKey, templateId, isMock };
};

/**
 * Send an OTP to the given phone number using MSG91
 * @param {string} phone - Mobile number with country code (e.g. 919876543210)
 * @returns {Promise<{success: boolean, message: string}>}
 */
export const sendOtp = async (phone) => {
    const { authKey, templateId, isMock } = getCredentials();

    if (isMock) {
        console.log(`\n=================== [MSG91 SMS GATEWAY - MOCK MODE] ===================`);
        console.log(`To: ${phone}`);
        console.log(`Action: Send OTP`);
        console.log(`OTP generated by MSG91 would be sent here.`);
        console.log(`For local testing, verify this phone using mock OTP '123456' or '1234'.`);
        console.log(`========================================================================\n`);
        return { success: true, message: 'OTP sent successfully (Simulated)' };
    }

    try {
        const response = await fetch('https://control.msg91.com/api/v5/otp', {
            method: 'POST',
            headers: {
                'authkey': authKey,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                template_id: templateId,
                mobile: phone
            })
        });

        const data = await response.json();
        
        if (response.ok && (data.type === 'success' || data.message === 'OTP sent successfully')) {
            return { success: true, message: data.message || 'OTP sent successfully' };
        } else {
            console.error('[MSG91] Error sending OTP:', data);
            throw new Error(data.message || 'Error response from MSG91 server');
        }
    } catch (error) {
        console.error('[MSG91] Network / API error sending OTP:', error.message);
        throw new Error(`Failed to send SMS OTP: ${error.message}`);
    }
};

/**
 * Verify an OTP code for the given phone number using MSG91
 * @param {string} phone - Mobile number with country code (e.g. 919876543210)
 * @param {string} otp - OTP code to verify
 * @returns {Promise<{success: boolean, message: string}>}
 */
export const verifyOtp = async (phone, otp) => {
    const { authKey, isMock } = getCredentials();

    if (isMock) {
        console.log(`[MSG91 MOCK] Verifying OTP '${otp}' for phone '${phone}'`);
        if (otp === '123456' || otp === '1234') {
            return { success: true, message: 'OTP verified successfully (Simulated)' };
        }
        return { success: false, message: 'Invalid OTP code. Please use 123456 or 1234.' };
    }

    try {
        // MSG91 OTP verify endpoint
        const url = `https://control.msg91.com/api/v5/otp/verify?otp=${encodeURIComponent(otp)}&mobile=${encodeURIComponent(phone)}`;
        const response = await fetch(url, {
            method: 'GET',
            headers: {
                'authkey': authKey
            }
        });

        const data = await response.json();

        // MSG91 returns type: "success" on verified or already verified OTPs
        if (response.ok && data.type === 'success') {
            return { success: true, message: data.message || 'OTP verified successfully' };
        } else {
            console.warn('[MSG91] Verification failed:', data);
            return { success: false, message: data.message || 'Invalid or expired OTP' };
        }
    } catch (error) {
        console.error('[MSG91] Network / API error verifying OTP:', error.message);
        return { success: false, message: `Failed to verify OTP: ${error.message}` };
    }
};
